spring:
  application:
    name: url-shortener-sb

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  jwtExpirationMs: ${JWT_EXPIRATION_MS}

logging:
  level:
    org:
      springframework:
        security: DEBUG
    url:
      shortener: DEBUG
